[package]
name = "web_blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-web = "4.3.1"
handlebars = { version = "4.3.6", features = ["dir_source"] }
serde_json = "1.0.93"

